spring.application.name=demoApi
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://143.106.241.4:3306/cl204068
spring.datasource.username=cl204068
spring.datasource.password=cl*07082008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect