// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_mock_web_api_key_koavy_health',
    appId: '1:564333524566:web:ca3709b82bf9d29c882855',
    messagingSenderId: '564333524566',
    projectId: 'koavy-health',
    authDomain: 'koavy-health.firebaseapp.com',
    storageBucket: 'koavy-health.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_mock_android_api_key_koavy_health',
    appId: '1:564333524566:android:da3709b82bf9d29c882855',
    messagingSenderId: '564333524566',
    projectId: 'koavy-health',
    storageBucket: 'koavy-health.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_mock_ios_api_key_koavy_health',
    appId: '1:564333524566:ios:ea3709b82bf9d29c882855',
    messagingSenderId: '564333524566',
    projectId: 'koavy-health',
    storageBucket: 'koavy-health.appspot.com',
    iosBundleId: 'com.koavy.app',
  );
}
